FROM ubuntu:14.04
MAINTAINER Irek Romaniuk
# Install
RUN sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list \
  apt-get update \
  apt-get -y upgrade \
  apt-get install -y build-essential \
  apt-get install -y software-properties-common \
  && yum -y install passwd sudo git wget openssl openssh openssh-server openssh-clients \
  && yum -y install mail postfix \
  rm -rf /var/lib/apt/lists/*

